<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link_ContactonAccount</name>
   <tag></tag>
   <elementGuidId>b559ff0a-1743-416c-b2c9-ea9924e97bcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@class='rlql-relatedListQuickLink']//div[@class='slds-media']//div[@class='slds-grid']//span[contains(text(),'Contacts')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
