<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SelectSelectionProduct</name>
   <tag></tag>
   <elementGuidId>2ae1fec2-83a7-40f8-be4e-77402099766d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//sb-i18n[text()='Select']//parent::paper-button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
