<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Save</name>
   <tag></tag>
   <elementGuidId>fa8f5bcd-ff36-48d4-b163-3789bc8b668b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//sb-custom-action[@name='Save']//paper-button[@id='mainButton']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
